##############################################################################################################################################
##                                                                                                                                          ##
##  vss_db_tables.py																														##
##------------------------------------------------------------------------------------------------------------------------------------------##
##                                                                                                                                          ##
##  Author: 		Joseph Armstrong (armstjc@mail.uc.edu)																					##
##	Description:	Houses databse table and view creation scripts for tables used by the app.												##
##                                                                                                                                          ##
##############################################################################################################################################

SQLITE_MLB_RETROSHEET_SCHEDULE_TABLE = """
    CREATE TABLE "mlb_retrosheet_schedule" (
	"date_id"	INT NOT NULL,
	"game_num"	INT NOT NULL,
	"day"	TEXT NOT NULL,
	"away_team_id"	TEXT NOT NULL,
	"away_team_leauge"	TEXT NOT NULL,
	"away_game_num"	INT NOT NULL,
	"home_team_id"	TEXT NOT NULL,
	"home_team_leauge"	TEXT,
	"home_game_num"	INT NOT NULL,
	"time_of_day"	TEXT NOT NULL,
	"delay_info"	TEXT,
	"makeup_date"	INT);
    """

SQLITE_MLB_RETROSHEET_PEOPLE_TABLE = """
CREATE TABLE "mlb_retrosheet_people" (
	"player_id"	TEXT NOT NULL UNIQUE,
	"last_name"	TEXT NOT NULL,
	"first_name"	TEXT,
	"nickname"	TEXT,
	"birthdate"	TEXT,
	"birth_city"	TEXT,
	"birth_state"	TEXT,
	"birth_country"	TEXT,
	"play_debut"	TEXT,
	"play_last_game"	TEXT,
	"mgr_debut"	TEXT,
	"mgr_last_game"	TEXT,
	"coach_debut"	TEXT,
	"coach_last_game"	TEXT,
	"ump_debut"	TEXT,
	"ump_last_game"	TEXT,
	"death_date"	TEXT,
	"death_city"	TEXT,
	"death_state"	TEXT,
	"death_country"	TEXT,
	"bats"	TEXT,
	"throws"	TEXT,
	"height"	TEXT,
	"weight"	INTEGER,
	"cemetery"	TEXT,
	"ceme_city"	TEXT,
	"ceme_state"	TEXT,
	"ceme_country"	TEXT,
	"ceme_note"	TEXT,
	"birth_name"	TEXT,
	"name_chg"	REAL,
	"bat_chg"	REAL,
	"hof"	TEXT,
	PRIMARY KEY("player_id"));
"""

SQLITE_MLB_RETROSHEET_BALLPARK_TABLE = """
CREATE TABLE "mlb_retrosheet_ballparks" (
	"park_id"	TEXT NOT NULL UNIQUE,
	"park_name"	TEXT NOT NULL,
	"park_alt_name"	TEXT,
	"park_city"	TEXT NOT NULL,
	"park_state"	TEXT NOT NULL,
	"park_start_date"	TEXT NOT NULL,
	"park_end_date"	TEXT,
	"park_leauge"	TEXT,
	"park_notes"	TEXT,
	PRIMARY KEY("park_id"));
"""

SQLITE_MLB_RETROSHEET_EJECTIONS_TABLE = """
CREATE TABLE "mlb_retrosheet_ejections" (
	"game_id"	TEXT NOT NULL,
	"date"	TEXT NOT NULL,
	"dh"	TEXT NOT NULL,
	"ejectee"	TEXT NOT NULL,
	"ejectee_name"	TEXT NOT NULL,
	"team"	TEXT NOT NULL,
	"job"	TEXT NOT NULL,
	"umpire"	TEXT NOT NULL,
	"umpire_name"	TEXT NOT NULL,
	"inning"	INTEGER NOT NULL,
	"reason"	TEXT NOT NULL);
"""

SQLITE_MLB_RETROSHEET_FRANCHISE_TABLE = """
CREATE TABLE "mlb_retrosheet_franchises" (
	"fran_id"	TEXT NOT NULL UNIQUE,
	"leauge"	TEXT,
	"city"	TEXT NOT NULL,
	"nickname"	TEXT NOT NULL,
	"first_year"	INTEGER NOT NULL,
	"last_year"	INTEGER NOT NULL,
	PRIMARY KEY("fran_id"));
"""

SQLITE_MLB_STATCAST_PBP_TABLE = """
CREATE TABLE "mlb_statcast_pbp" (
	"pitch_type"	TEXT,
	"game_date"	TEXT,
	"release_speed"	REAL,
	"release_pos_x"	REAL,
	"release_pos_z"	REAL,
	"player_name"	TEXT,
	"batter"	INTEGER,
	"pitcher"	INTEGER,
	"events"	TEXT,
	"description"	TEXT,
	"spin_dir"	REAL,
	"spin_rate_deprecated"	REAL,
	"break_angle_deprecated"	REAL,
	"break_length_deprecated"	REAL,
	"zone"	INTEGER,
	"des"	TEXT,
	"game_type"	TEXT,
	"stand"	TEXT,
	"p_throws"	TEXT,
	"home_team"	TEXT,
	"away_team"	TEXT,
	"type"	TEXT,
	"hit_location"	INTEGER,
	"bb_type"	TEXT,
	"balls"	INTEGER,
	"strikes"	INTEGER,
	"game_year"	INTEGER,
	"pfx_x"	REAL,
	"pfx_z"	REAL,
	"plate_x"	REAL,
	"plate_z"	REAL,
	"on_3b"	INTEGER,
	"on_2b"	INTEGER,
	"on_1b"	INTEGER,
	"outs_when_up"	INTEGER,
	"inning"	INTEGER,
	"inning_topbot"	TEXT,
	"hc_x"	REAL,
	"hc_y"	REAL,
	"tfs_deprecated"	REAL,
	"tfs_zulu_deprecated"	REAL,
	"fielder_2"	INTEGER,
	"umpire"	REAL,
	"sv_id"	REAL,
	"vx0"	REAL,
	"vy0"	REAL,
	"vz0"	REAL,
	"ax"	REAL,
	"ay"	REAL,
	"az"	REAL,
	"sz_top"	REAL,
	"sz_bot"	REAL,
	"hit_distance_sc"	INTEGER,
	"launch_speed"	REAL,
	"launch_angle"	INTEGER,
	"effective_speed"	REAL,
	"release_spin_rate"	INTEGER,
	"release_extension"	REAL,
	"game_pk"	INTEGER,
	"pitcher.1"	INTEGER,
	"fielder_2.1"	INTEGER,
	"fielder_3"	INTEGER,
	"fielder_4"	INTEGER,
	"fielder_5"	INTEGER,
	"fielder_6"	INTEGER,
	"fielder_7"	INTEGER,
	"fielder_8"	INTEGER,
	"fielder_9"	INTEGER,
	"release_pos_y"	REAL,
	"estimated_ba_using_speedangle"	REAL,
	"estimated_woba_using_speedangle"	REAL,
	"woba_value"	REAL,
	"woba_denom"	INTEGER,
	"babip_value"	INTEGER,
	"iso_value"	INTEGER,
	"launch_speed_angle"	REAL,
	"at_bat_number"	INTEGER,
	"pitch_number"	INTEGER,
	"pitch_name"	TEXT,
	"home_score"	INTEGER,
	"away_score"	INTEGER,
	"bat_score"	INTEGER,
	"fld_score"	INTEGER,
	"post_away_score"	INTEGER,
	"post_home_score"	INTEGER,
	"post_bat_score"	INTEGER,
	"post_fld_score"	INTEGER,
	"if_fielding_alignment"	TEXT,
	"of_fielding_alignment"	TEXT,
	"spin_axis"	INTEGER,
	"delta_home_win_exp"	REAL,
	"delta_run_exp"	REAL,
	"month"	INTEGER,
	"day"	INTEGER
);
"""
SQLITE_MLB_RETROSPLITS_PLAYER_BOX = """
CREATE TABLE "mlb_retrosplits_player_box" (
	"game.key"	TEXT,
	"game.source"	TEXT,
	"game.date"	TEXT,
	"game.number"	INTEGER,
	"appear.date"	TEXT,
	"site.key"	TEXT,
	"season.phase"	TEXT,
	"team.alignment"	INTEGER,
	"team.key"	TEXT,
	"opponent.key"	TEXT,
	"person.key"	TEXT,
	"slot"	INTEGER,
	"seq"	INTEGER,
	"B_G"	INTEGER,
	"B_PA"	INTEGER,
	"B_AB"	INTEGER,
	"B_R"	INTEGER,
	"B_H"	INTEGER,
	"B_TB"	INTEGER,
	"B_2B"	INTEGER,
	"B_3B"	INTEGER,
	"B_HR"	INTEGER,
	"B_HR4"	INTEGER,
	"B_RBI"	INTEGER,
	"B_GW"	INTEGER,
	"B_BB"	INTEGER,
	"B_IBB"	INTEGER,
	"B_SO"	INTEGER,
	"B_GDP"	INTEGER,
	"B_HP"	INTEGER,
	"B_SH"	INTEGER,
	"B_SF"	INTEGER,
	"B_SB"	INTEGER,
	"B_CS"	INTEGER,
	"B_XI"	INTEGER,
	"B_G_DH"	INTEGER,
	"B_G_PH"	INTEGER,
	"B_G_PR"	INTEGER,
	"P_G"	INTEGER,
	"P_GS"	INTEGER,
	"P_CG"	INTEGER,
	"P_SHO"	INTEGER,
	"P_GF"	INTEGER,
	"P_W"	INTEGER,
	"P_L"	INTEGER,
	"P_SV"	INTEGER,
	"P_OUT"	INTEGER,
	"P_TBF"	INTEGER,
	"P_AB"	INTEGER,
	"P_R"	INTEGER,
	"P_ER"	INTEGER,
	"P_H"	INTEGER,
	"P_TB"	INTEGER,
	"P_2B"	INTEGER,
	"P_3B"	INTEGER,
	"P_HR"	INTEGER,
	"P_HR4"	INTEGER,
	"P_BB"	INTEGER,
	"P_IBB"	INTEGER,
	"P_SO"	INTEGER,
	"P_GDP"	INTEGER,
	"P_HP"	INTEGER,
	"P_SH"	INTEGER,
	"P_SF"	INTEGER,
	"P_XI"	INTEGER,
	"P_WP"	INTEGER,
	"P_BK"	INTEGER,
	"P_IR"	INTEGER,
	"P_IRS"	INTEGER,
	"P_GO"	INTEGER,
	"P_AO"	INTEGER,
	"P_PITCH"	INTEGER,
	"P_STRIKE"	INTEGER,
	"F_1B_POS"	INTEGER,
	"F_1B_G"	INTEGER,
	"F_1B_GS"	INTEGER,
	"F_1B_OUT"	INTEGER,
	"F_1B_TC"	INTEGER,
	"F_1B_PO"	INTEGER,
	"F_1B_A"	INTEGER,
	"F_1B_E"	INTEGER,
	"F_1B_DP"	INTEGER,
	"F_1B_TP"	INTEGER,
	"F_2B_POS"	INTEGER,
	"F_2B_G"	INTEGER,
	"F_2B_GS"	INTEGER,
	"F_2B_OUT"	INTEGER,
	"F_2B_TC"	INTEGER,
	"F_2B_PO"	INTEGER,
	"F_2B_A"	INTEGER,
	"F_2B_E"	INTEGER,
	"F_2B_DP"	INTEGER,
	"F_2B_TP"	INTEGER,
	"F_3B_POS"	INTEGER,
	"F_3B_G"	INTEGER,
	"F_3B_GS"	INTEGER,
	"F_3B_OUT"	INTEGER,
	"F_3B_TC"	INTEGER,
	"F_3B_PO"	INTEGER,
	"F_3B_A"	INTEGER,
	"F_3B_E"	INTEGER,
	"F_3B_DP"	INTEGER,
	"F_3B_TP"	INTEGER,
	"F_SS_POS"	INTEGER,
	"F_SS_G"	INTEGER,
	"F_SS_GS"	INTEGER,
	"F_SS_OUT"	INTEGER,
	"F_SS_TC"	INTEGER,
	"F_SS_PO"	INTEGER,
	"F_SS_A"	INTEGER,
	"F_SS_E"	INTEGER,
	"F_SS_DP"	INTEGER,
	"F_SS_TP"	INTEGER,
	"F_OF_POS"	INTEGER,
	"F_OF_G"	INTEGER,
	"F_OF_GS"	INTEGER,
	"F_OF_OUT"	INTEGER,
	"F_OF_TC"	INTEGER,
	"F_OF_PO"	INTEGER,
	"F_OF_A"	INTEGER,
	"F_OF_E"	INTEGER,
	"F_OF_DP"	INTEGER,
	"F_OF_TP"	INTEGER,
	"F_LF_POS"	INTEGER,
	"F_LF_G"	INTEGER,
	"F_LF_GS"	INTEGER,
	"F_LF_OUT"	INTEGER,
	"F_LF_TC"	INTEGER,
	"F_LF_PO"	INTEGER,
	"F_LF_A"	INTEGER,
	"F_LF_E"	INTEGER,
	"F_LF_DP"	INTEGER,
	"F_LF_TP"	INTEGER,
	"F_CF_POS"	INTEGER,
	"F_CF_G"	INTEGER,
	"F_CF_GS"	INTEGER,
	"F_CF_OUT"	INTEGER,
	"F_CF_TC"	INTEGER,
	"F_CF_PO"	INTEGER,
	"F_CF_A"	INTEGER,
	"F_CF_E"	INTEGER,
	"F_CF_DP"	INTEGER,
	"F_CF_TP"	INTEGER,
	"F_RF_POS"	INTEGER,
	"F_RF_G"	INTEGER,
	"F_RF_GS"	INTEGER,
	"F_RF_OUT"	INTEGER,
	"F_RF_TC"	INTEGER,
	"F_RF_PO"	INTEGER,
	"F_RF_A"	INTEGER,
	"F_RF_E"	INTEGER,
	"F_RF_DP"	INTEGER,
	"F_RF_TP"	INTEGER,
	"F_C_POS"	INTEGER,
	"F_C_G"	INTEGER,
	"F_C_GS"	INTEGER,
	"F_C_OUT"	INTEGER,
	"F_C_TC"	INTEGER,
	"F_C_PO"	INTEGER,
	"F_C_A"	INTEGER,
	"F_C_E"	INTEGER,
	"F_C_DP"	INTEGER,
	"F_C_TP"	INTEGER,
	"F_C_PB"	INTEGER,
	"F_C_XI"	INTEGER,
	"F_P_POS"	INTEGER,
	"F_P_G"	INTEGER,
	"F_P_GS"	INTEGER,
	"F_P_OUT"	INTEGER,
	"F_P_TC"	INTEGER,
	"F_P_PO"	INTEGER,
	"F_P_A"	INTEGER,
	"F_P_E"	INTEGER,
	"F_P_DP"	INTEGER,
	"F_P_TP"	INTEGER);
"""

SQLITE_VACUUM_COMMAND = "VACUUM \"main\""